export const TOOLTIP_MAXIMUM_WIDTH = 400;
export const TOOLTIP_MAXIMUM_HEIGHT = 600;
export const TOOLTIP_HORIZONTAL_PADDING = 24;
export const TOOLTIP_VERTICAL_PADDING = 24;
export const TOOLTIP_OFFSET_FOR_ANCHOR = 3;

export const TOOLTIP_HORIZONTAL_MARGIN = 5;
export const TOOLTIP_VERTICAL_MARGIN = 5;

export const TOOLTIP_ANCHOR_HORIZONTAL_WIDTH = 35;
export const TOOLTIP_ANCHOR_HORIZONTAL_HEIGHT = 10;

export const TOOLTIP_ANCHOR_VERTICAL_WIDTH = 10;
export const TOOLTIP_ANCHOR_VERTICAL_HEIGHT = 35;