export const TOOLTIP_MAXIMUM_WIDTH = 400;
export const TOOLTIP_MAXIMUM_HEIGHT = 600;

export const TOOLTIP_HORIZONTAL_PADDING = 24;
export const TOOLTIP_VERTICAL_PADDING = 24;
export const TOOLTIP_OFFSET_FOR_POINTER = 3;

export const TOOLTIP_HORIZONTAL_MARGIN = 5;
export const TOOLTIP_VERTICAL_MARGIN = 5;

export const TOOLTIP_POINTER_HORIZONTAL_WIDTH = 35;
export const TOOLTIP_POINTER_HORIZONTAL_HEIGHT = 10;

export const TOOLTIP_POINTER_VERTICAL_WIDTH = 10;
export const TOOLTIP_POINTER_VERTICAL_HEIGHT = 35;

export const TOOLTIP_OPACITY_ANIMATION_DURATION = 500;
export const TOOLTIP_SHAKE_ANIMATION_DURATION = 300;

export const TOOLTIP_DEFAULT_BACKGROUND_COLOR = "#E8EEF7";
export const TOOLTIP_BORDER_RADIUS = 5;
